# Generated by Django 2.0.1 on 2018-02-05 21:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfName', models.TextField()),
                ('professor_name', models.TextField()),
                ('subjectName', models.TextField()),
                ('pdf_title', models.TextField()),
                ('pdf_desc', models.TextField()),
                ('pdf_doc', models.FileField(upload_to='documents/')),
                ('pdf_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), default=list, null=True, size=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
