# Generated by Django 2.0.1 on 2018-02-12 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20180212_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='pdf_doc',
        ),
        migrations.AddField(
            model_name='pdf',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
