# Generated by Django 2.0.1 on 2018-02-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20180213_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='pdf_title',
        ),
    ]
