# Generated by Django 2.0.1 on 2018-02-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='count',
        ),
    ]
