# Generated by Django 2.0.1 on 2018-03-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_remove_tag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='year',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='freshman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='junior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='phD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='sophomore',
            field=models.BooleanField(default=False),
        ),
    ]
